создал несколько секций
bogachenkopetr/holidays pull request #1
Opened 2020-04-23 15:00 UTC by bogachenkopetr

2020-04-23 20:42 UTC, abahachenka commented
1. Нужно настроить prepros, чтобы он конвертировал только styles.scss файл, а не все сразу.

2020-04-23 21:23 UTC, abahachenka requested changes

2020-04-23 21:23 UTC, abahachenka commented on index.html
> -            <nav class="topnav">
Почему удалил nav?  Это очень нужный тег. Он указывает, что в этом месте навигация.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                <img src="img/logo-top.png" alt="logo-top">
Список не может разрываться. Ты должен вынести img за пределы списка.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +           <div class="top_welcome">
Этот div бесполезен. Он никаких стилей не добавляет.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +            <header class="ideas_title">
С именами класса путаница. Это не совсем title, это header. Слово title обычно используется для заголовков.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                <ul class="ideas_photo">
Лучше не _photo (одно), а _photos

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                            <p class="ideas_button_center"><a class="ideas_beach" href="">Beachfront Escapes</a></p>
Зачем каждой ссылке делать свой класс?
href не должен быть пустым

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                            <a href="#"><img class="avatar" src="img/ideas_beach.png" alt="ideas_beach"></a>
avatar тоже странное название для картинки с туристической тематикой. Аватар означает фото пользователя.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                            <a href="#"><img class="avatar" src="img/ideas_beach.png" alt="ideas_beach"></a>
Не нужно заполнять alt безсмысленной информацией. Оставляй их просто пустыми либо пиши смысловой альтернативный текст, описывающий картинку.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                <h3>Recent holiday locations</h3>
Почему здесь h3, а не h2? Эта секция с предыдущей никак не связана, поэтому иерархия идет от главного заголовка сайта.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                <h4>Why we are different</h4>
Тоже самое. Не h4, а h2. Это самостоятельная секция.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                    <div class="icon_why_us">
Старайся использовать одинаковую стилистику именования классов. Если у тебя идут классы в секции why_us_list, why_us_item, то логичено чтобы было why_us_icon

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                        <h5>Tailor-Made Packages</h5>
Не h5, а h3. Уровень на 1 ниже, чем у заголовка секции.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                    </p>
Криво отформатировано

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                        <li><span>Information</span></li>
Верхние пункты представляют собой список первого уровня. А все, что под ними - вложенные списки. То есть тебе здесь нужно переделать на вложенные списки.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                    <ul class="list_left_information">
Криво отформатировано

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                    <ul class="list_left_experiences">
Не нужно плодить столько классов для каждой колонки. Тут можно обойтись одним классом на всех.

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                        <li><span>.</span></li>
Такого быть не должно

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                <div class="foter_list_right">
footer с двумя o

2020-04-23 21:23 UTC, abahachenka commented on index.html
> +                        <li>Email: info@aztechdesign.co</li><br><br>
Списки не должны разрываться другими тегами. Никаких br тут быть не должно

2020-04-23 21:23 UTC, abahachenka commented on scss/footer.scss
> +    color: #fff;
Цвета должны быть перенесены в переменные

2020-04-23 21:23 UTC, abahachenka commented on scss/footer.scss
> +    padding: 50px 0 50px 0;
Можно сократить до двух параметров

2020-04-23 21:23 UTC, abahachenka commented on scss/footer.scss
> +         font-weight: 600;
Эти строки можно объединить в одну

2020-04-23 21:23 UTC, abahachenka commented on scss/footer.scss
> +.foter_list_right{
Очень много одинаковых стилей с footer_list_left. Надо общее объединить.

2020-04-23 21:23 UTC, abahachenka commented on scss/footer.scss
> +}
Когда переделаешь на вложенные списки, эти вещи должны исчезнуть.

2020-04-23 21:23 UTC, abahachenka commented on scss/footer.scss
> +
Максимум 1 пустая строка в конце

2020-04-23 21:23 UTC, abahachenka commented on scss/header.scss
> +    }
Криво отформатировано

2020-04-23 21:23 UTC, abahachenka commented on scss/ideas.scss
> +    background: #fff;
Цвет - в переменную

2020-04-23 21:23 UTC, abahachenka commented on scss/ideas.scss
> +    color: #fff;
цвет - в переменную

2020-04-23 21:23 UTC, abahachenka commented on scss/ideas.scss
> +    color:#454851;
цвет - в переменную

2020-04-23 21:23 UTC, abahachenka commented on scss/ideas.scss
> +    border: 1px solid #cccccc;
цвет - в переменную

2020-04-23 21:23 UTC, abahachenka commented on scss/ideas.scss
> +}
Эти классы не нужны. Можно обойтись одним классом на троих. Большинство стилей просто продублировано, и паддинги подгонять вообще не надо.

2020-04-23 21:23 UTC, abahachenka commented on scss/ideas.scss
> +
Удилить лишние пустые строки

2020-04-23 21:23 UTC, abahachenka commented on scss/properties.scss
> +}
Вот тут надо бы добавить пустую строку в конце

2020-04-23 21:23 UTC, abahachenka commented on scss/send-us.scss
> +.send_us{
Очень странное название и класса и файла. Лучше назови contact us.

2020-04-23 21:23 UTC, abahachenka commented on scss/slider.scss
> +}
нужна пустая строка

2020-04-23 21:23 UTC, abahachenka commented on scss/send-us.scss
> +}
нужна пустая строка

2020-04-23 21:23 UTC, abahachenka commented on scss/style.scss
> +@import 'send-us';
пустая строка

2020-04-23 21:23 UTC, abahachenka commented on scss/why-us.scss
> +    h5{
Раздели блоки пустой строкой

2020-04-23 21:23 UTC, abahachenka commented on scss/why-us.scss
> +        font-weight: 300;
Можно объединить

2020-04-25 12:29 UTC, bogachenkopetr commented
внес исправления по коментам

2020-05-02 20:53 UTC, closed without merging