Header 2
bogachenkopetr/holidays pull request #2
Opened 2020-04-29 12:48 UTC by bogachenkopetr

2020-04-29 21:24 UTC, abahachenka requested changes

2020-04-29 21:24 UTC, abahachenka commented on index.html
> +                    </div>
Один tab назад

2020-04-29 21:24 UTC, abahachenka commented on index.html
> +                <button class="button_slider" type="radio">&#8594;</button>
Type=radio здесь не нужен

2020-04-29 21:24 UTC, abahachenka commented on scss/header.scss
> +        &:nth-child(2){
Добавить пустую строку после 23-ей строки

2020-04-29 21:24 UTC, abahachenka commented on scss/header.scss
> +        margin-right:420px;
Tab

2020-04-29 21:24 UTC, abahachenka commented on scss/slider.scss
> +    background: #fff;
Вставь цвет через переменную

2020-04-29 21:24 UTC, abahachenka commented on scss/slider.scss
> +        color: #999999;
Вставь цвет через переменную

2020-04-29 21:24 UTC, abahachenka commented on scss/slider.scss
> +    color: #fff;
Вставь цвет через переменную

2020-04-29 21:24 UTC, abahachenka commented on scss/header.scss
> +        left: 570px;
Поставь 37%

2020-04-29 21:24 UTC, abahachenka commented on scss/header.scss
> +        margin-right:420px;
Поставь здесь 395px, мне кажется так симметричнее

2020-04-29 21:24 UTC, abahachenka commented on index.html
> +            <img src="img/logo-top.png" alt="logo-top">
Да и совсем забыла напомнить, что логотип это всегда ссылка на домашнюю страницу. href="/"

2020-04-29 21:24 UTC, abahachenka commented on scss/slider.scss
> +    height: 100vh;
Это строка не имеет смысла, так как ниже она перезаписывается height: 690px;

2020-04-29 21:24 UTC, abahachenka commented on scss/slider.scss
> +    input{
Надо добавить стиль при фокусе. Добавляешь для инпута вложенный стиль 
`&:focus { 
      // тут стили 
}`

2020-05-01 09:20 UTC, bogachenkopetr commented
внес исправления

2020-05-01 09:51 UTC, merged