Ideas
bogachenkopetr/holidays pull request #4
Opened 2020-05-03 09:08 UTC by bogachenkopetr

2020-05-19 20:38 UTC, abahachenka requested changes

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                <h3>Recent holiday locations</h3>
По иерархии заголовков, здесь больше подходит H2

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                            <img class="branding" src="img/thalie.png" alt="thalie">
Все твои альты не несут смысловой нагрузки. Лучше просто оставляй их пустыми alt=""

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                            <h4>Thalie 5</h4>
Тут будет h3

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                            <a href="#"><img class="avatar" src="img/ideas_beach.png" alt="ideas_beach"></a>
Уже писала, но напишу еще раз. Оставляй alt пустым(alt=""). Непонятные слова с подчеркиванием никак не помогают пользователю разобраться что там за изображение. Смотрится не очень умно.

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                <img class="rhombus" src="img/rhombus.png" alt="rhombus">
alt=""

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                            <p class="ideas_button_center"><a class="ideas_beach" href="">Beachfront Escapes</a></p>
href не должен быть пустым. Ставь заглушку #

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                        <div class="button_center_wrapper">
Название класса не совсем подходящее, как по мне. Вроде относится к кнопке, но там не только кнопка. И не связывается с блоком ideas. Переименуй лучше в что-то типа ideas_item_wrapper

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                            <a href="#"><img class="avatar" src="img/ideas_beach.png" alt="ideas_beach"></a>
Уже как-то писала, но слово avatar всегда относится к фотке пользователя-человека. Сюда такое слово не подходит. Назови что-то типа ideas_photo или ideas_item_photo

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +            <div class="ideas_photo_wrapper">
Cоздается впечатление, что здесь обертка лишь для одной фотки. Лучше было бы ideas_photos_wrapper

2020-05-19 20:38 UTC, abahachenka commented on index.html
> +                                    <span class="quantity">5</span> <span class="hint">                 <span class="hint_inner">bath</span>
Отформатируй код, чтобы элемент hint был с новой строки.

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +            font: bold 30px 'kepler_std';
Повторяющаяся информация. Оставляй только размер шрифта.

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +            font: bold 48px 'kepler_std';
Повторяющаяся информация. Оставляй только размер шрифта.

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +    background: #fff;
Цвет в переменную

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +    color: #fff;
И тут тоже

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +        font: bold 16px 'kepler_std', serif;
Только размер шрифта

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +    font: bold 20px 'kepler_std', serif;
Зачем тут вдруг понадобился serif?

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +    color:#454851;
Цвет в переменную

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +    border: 1px solid #cccccc;
Цвет в переменную

2020-05-19 20:38 UTC, abahachenka commented on scss/ideas.scss
> +.ideas_group{
А чем этот класс отличается от ideas_beach и зачем он нужен? Очень много дублированной информации. Пересмотри стили. Я думаю можно обойтись одним общим классом на все подобные элементы. (Относится и к ideas_city)

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +
Лишняя пустая строка

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +.properties_photo_album > li{
Перенести в предыдущий блок. Связать через &

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +}
Тоже перенести в блок .properties_photo_album

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +        height: 60px;
Tab

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +        width: 33.3333%;
Tab

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +    h4{
Добавь пустую строку

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +.button_properties{
Название класса ни о чем. Что эта кнопка делает? Это book now? Назови тогда properties_book_button

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +        }
Если ничего нет, то удаляем

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +        background: #454851;
цвет в переменную

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +            &:before{
Добавь пустую строку

2020-05-19 20:38 UTC, abahachenka commented on scss/properties.scss
> +                border-right: 10px solid #454851;
цвет в переменную

2020-05-19 20:40 UTC, abahachenka commented
Выявлены проблемы с 992. Мы с тобой неправильно тестировали. Открой страницу четко на ширине 992. Она отличается от полного экрана. Попробуй поправить по-максимуму.

2020-05-21 20:12 UTC, abahachenka requested changes

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="hint">                       <span class="hint_inner">bath</span>
hint_inner тоже с новой строки. Весь код должен иметь ступенчатую структуру, согласно уровню вложенности.

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">beachfront</span>
hint с новой строки. hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">pool</span>
hint с новой строки. hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                            <h4>Montage Kapalua</h4>
Я думала ты догадаешься, что если в первой карточке поменялся заголовок на h3, то и тут тоже надо поменять.

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                            <h4>Casa Del Agua</h4>
И тут h3

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                            <h4>Casa Jaguar</h4>
h3

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <img class="properties_logo" src="img/bed.png" alt=""><span class="quantity">1</span> <span class="hint">                 <span class="hint_inner">bed</span>
hint с новой строки. hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity">1</span> <span class="hint">                 <span class="hint_inner">bath</span>
hint с новой строки. hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">beachfront</span>
hint с новой строки. hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">pool</span>
hint с новой строки. hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <img class="properties_logo" src="img/bed.png" alt=""><span class="quantity">4</span> <span class="hint">                 <span class="hint_inner">bed</span>
quantity с новой строки. 
hint с новой строки. 
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity">4</span> <span class="hint">                 <span class="hint_inner">bath</span>
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">beachfront</span>
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">beachfront</span>
Если quantity пустой, то зачем он здесь?

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">pool</span>
Пустой quantity, лучше удалить.
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <img class="properties_logo" src="img/bed.png" alt=""><span class="quantity">4</span> <span class="hint">                 <span class="hint_inner">bed</span>
quantity с новой строки
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity">4</span> <span class="hint">                 <span class="hint_inner">bath</span>
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">beachfront</span>
Пустой quantity!
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on index.html
> +                                    <span class="quantity"></span> <span class="hint">                 <span class="hint_inner">pool</span>
Пустой quantity!
hint с новой строки.
hint_inner тоже с новой строки

2020-05-21 20:12 UTC, abahachenka commented on scss/ideas.scss
> +        font: bold 24px 'kepler_std', serif;
Ты вверху почему-то убрал название шрифта на строке 74, а тут вдруг появился шрифт. Логичнее, чтобы вверху было название шрифта, а тут только менялся размер. Serif у тебя то есть, то нет. Определись, нужно его писать или нет.

2020-05-21 20:12 UTC, abahachenka commented on scss/properties.scss
> +.properties_photo_album > li{
Посмотри файл ideas.scss, начиная со строки 36. Там есть пример использования &.

2020-05-21 20:12 UTC, abahachenka commented on scss/properties.scss
> +    background: #f31131;
цвет в переменную

2020-05-21 20:12 UTC, abahachenka commented on scss/properties.scss
> +    color: #fff;
цвет в переменную

2020-05-22 11:06 UTC, bogachenkopetr commented on index.html
> +                            <h4>Montage Kapalua</h4>
забыл(

2020-05-22 11:44 UTC, bogachenkopetr commented
внес исправления по замечаниям

2020-05-24 20:03 UTC, merged