создал мобильную версию секции send_us
bogachenkopetr/holidays pull request #7
Opened 2020-05-27 15:58 UTC by bogachenkopetr

2020-05-28 06:19 UTC, abahachenka requested changes

2020-05-28 06:19 UTC, abahachenka commented on index.html
> +                <div class="form_input">
Должен быть тег form и атрибут action

2020-05-28 06:19 UTC, abahachenka commented on index.html
> +                <button class="button_send_us">SEND</button>
Эта кнопка должна быть внутри формы, иначе форма не отправится. И желательно, чтобы это был не button, а input type="submit"

2020-05-28 06:19 UTC, abahachenka commented on scss/contact.scss
> +        height: 28px;
Тут лучше бы округлить эту величину до кратного 5.

2020-05-28 06:19 UTC, abahachenka commented on scss/contact.scss
> +        padding: 5px 5px;
Можно сократить до одного параметра

2020-05-28 06:19 UTC, abahachenka commented on scss/contact.scss
> +            font-size: 16px;
Не нужно. Уже есть в предыдущем медиа-запросе

2020-05-28 06:19 UTC, abahachenka commented on scss/send-us.scss
> +.send_us {
этот файл удали

2020-05-28 06:30 UTC, abahachenka requested changes

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    height: 100vh;
это сильно много, особенно на большом экране. На мобильном можешь оставить, а на большом экране - как по макету померяй

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    height: 250px;
это должно регулироваться само засчет внутреннего контента, паддингов и маржинов

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    width: 220px;
Ширину лучше задать в процентах, чтобы форма растягивалась

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +        width: 150px;
НЕТ! Ты ширину задаешь родителю, а тут 100%

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    font: normal 13px 'kepler_std', sans-serif;
тут шрифт не работает. Может убери sans-serif в конце. Кнопка по стилю должна быть такая же как в properties.

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    position: absolute;
Никаких абсолютов здесь не нужно. Кнопка идет в нормальном потоке контента. Регулируй отступы маржинами

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    left: 35px;
этих тоже вэк отсюда

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +        bottom: 35px;
удалить

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +        left: 45px;
удалить

2020-05-28 06:30 UTC, abahachenka commented on scss/contact.scss
> +    text-align: center;
удали это. В макете никаких центров нету

2020-05-28 12:12 UTC, bogachenkopetr commented
внес исправления

2020-05-28 21:23 UTC, abahachenka requested changes

2020-05-28 21:23 UTC, abahachenka commented on index.html
> +                    <button class="button_send_us">SEND</button>
<input type="submit" value="Send" class="button_send_us" />

2020-05-28 21:23 UTC, abahachenka commented on index.html
> +                    <input type="text" name="message" placeholder="Message">
Это поле под очень большим сомнением. Обычно под сообщение отводится textarea, а не input text

2020-05-28 21:23 UTC, abahachenka commented on scss/contact.scss
> +
лишняя строчка

2020-05-28 21:23 UTC, abahachenka commented on scss/contact.scss
> +    font: normal 13px 'kepler_std' sans-serif;
тут или должна быть запятая перед sans-serif или его быть не должно вообще

2020-05-29 08:17 UTC, bogachenkopetr commented on index.html
> +                    <input type="text" name="message" placeholder="Message">
в следующий раз)

2020-05-29 08:18 UTC, bogachenkopetr commented
внес изменения

2020-05-30 11:12 UTC, merged