создал секцию footer(без мобильной)
bogachenkopetr/holidays pull request #8
Opened 2020-05-31 09:46 UTC by bogachenkopetr

2020-06-03 18:51 UTC, abahachenka requested changes

2020-06-03 18:51 UTC, abahachenka commented on index.html
> +                <li class="column"><a href="">Information</a>
В ссылке нужна заглушка. Саму ссылку перенести на новую строку.

2020-06-03 18:51 UTC, abahachenka commented on index.html
> +                <li class="column"><a href="#">Experiences</a>
Ссылку на новую строку.

2020-06-03 18:51 UTC, abahachenka commented on index.html
> +                <li class="column"><a href="#">Themes</a>
Ссылку на новую строку

2020-06-03 18:51 UTC, abahachenka commented on index.html
> +                <li class="column"><a href="#">Popular destinations</a>
Ссылку на новую строку.

2020-06-03 18:51 UTC, abahachenka commented on index.html
> +
Лишняя строка

2020-06-03 18:51 UTC, abahachenka commented on index.html
> +    </body>
Либо тут либо блок footer надо выровнять

2020-06-03 18:51 UTC, abahachenka commented on scss/footer.scss
> +        font: normal 14px 'montserrat';
Дабы не задавать параметры шрифта несколько раз для разных элементов, можно эту запись вынести для блока footer_list_right, а для h2 лишь указать font-size: 16px

2020-06-03 18:51 UTC, abahachenka commented on scss/footer.scss
> +        font: normal 18px 'montserrat';
Слишком крупный шрифт. Как по мне, 16 лучше.

2020-06-03 18:51 UTC, abahachenka commented on scss/footer.scss
> +        margin-bottom: 25px;
Очень большой промежуток получается. Сделай хотя бы 10-15px

2020-06-03 18:51 UTC, abahachenka commented on scss/footer.scss
> +        line-height: 1.8;
И это тогда уменьши тоже

2020-06-03 18:51 UTC, abahachenka commented on scss/footer.scss
> +    a {
Надо бы добавить еще эффект на hover, чтобы визуально было видно, что мы наводим на ссылку. Достаточно добавить подчеркивание при наведении

2020-06-04 07:29 UTC, bogachenkopetr commented
внес исправления по замечаниям

2020-06-07 20:36 UTC, abahachenka requested changes

2020-06-07 20:36 UTC, abahachenka commented on scss/footer.scss
> +    a:hover {
Здесь должны быть стили и просто для 'a'. Ты перенес цвет в hover и у тебя слетел цвет у ссылок

2020-06-07 20:36 UTC, abahachenka commented on scss/footer.scss
> +        font: normal 14px 'montserrat';
Задай шрифт до media-запроса. А то получается, что параметры шрифта начинают работать только с 992

2020-06-08 10:01 UTC, bogachenkopetr commented
внес исправления

2020-06-10 20:23 UTC, merged